### PR TITLE
PR: Misc fixes

### LINKED ISSUE #53: Change readme image url for complete url

### LINKED ISSUE #54: Add build and dist to .gitignore

### PR DESCRIPTION
**Pull request by rlaverde**
Some miscellaneous fixes for 0.1.1 release

Fixes #53 
Fixes #54 
Remove and regenerate coveralls badge, add it to circle CI setup

### CODE REVIEW

**Comment by ccordoba12** [comment]
Why did you remove the repo token?

**Comment by goanpeca** [comment]
>Why did you remove the repo token?

@ccordoba12, those tokens should not be public, so I told @rlaverde to move them to the CI variables

**Comment by rlaverde** [comment]
@ccordoba12 As @goanpeca says, I move it to CI setup, should we remove and regenerate this token from other plugins?

**Comment by ccordoba12** [comment]
> should we remove and regenerate this token from other plugins?

Ok, that seems reasonable.

**Comment by rlaverde** [comment]
This PR is ready, and also 0.1.1 release 😄 

is ok to add a new dependency (matplotlib)? It's necessary for almost all renders, I don't know why It isn't a Pweave dependency 😞

**Comment by ccordoba12** [comment]
> is ok to add a new dependency (matplotlib)?

Sure, no problem.

----

Please use this version in staged-recipes to avoid skipping Python 2 to readd it again once we get the feedstock.

**Pull request merged**
