### PR TITLE
PR: Activate continuous integration

### LINKED ISSUE #13: Add basic tests and activate CI

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #13 #12

### CODE REVIEW

**Comment by ccordoba12** [comment]
I just activated support for this repo in Circle. Please:

1. Use the `circle.yml` file from `spyder-notebook` here.
2. Add a simple test to verify that everything is working correctly.

**Comment by ccordoba12** [comment]
There's no conda package for `pweave`, so you need to install it with pip.

**Comment by ccordoba12** [comment]
I mean, that's the error Circle is complaining about :-)

**Comment by goanpeca** [comment]
There is... https://github.com/conda-forge/pweave-feedstock we just need to copy it to the spyder-ide channel

**Comment by rlaverde** [comment]
I used the one from `mpastell` channel, I'm not sure if it's the same

**Comment by goanpeca** [comment]
@rlaverde please copy to the spyder-ide channel and use that one

**Comment by ccordoba12** [comment]
Looks good to me, we just need to use `pweave` from conda-forge, but after being copied to the `spyder-ide` channel.

**Pull request merged**
